// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/person/personal.proto

package personal

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseModel_StatusCode int32

const (
	ResponseModel_FAIL    ResponseModel_StatusCode = 0
	ResponseModel_SUCCESS ResponseModel_StatusCode = 1
)

var ResponseModel_StatusCode_name = map[int32]string{
	0: "FAIL",
	1: "SUCCESS",
}

var ResponseModel_StatusCode_value = map[string]int32{
	"FAIL":    0,
	"SUCCESS": 1,
}

func (x ResponseModel_StatusCode) String() string {
	return proto.EnumName(ResponseModel_StatusCode_name, int32(x))
}

func (ResponseModel_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{4, 0}
}

type GetAllModel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllModel) Reset()         { *m = GetAllModel{} }
func (m *GetAllModel) String() string { return proto.CompactTextString(m) }
func (*GetAllModel) ProtoMessage()    {}
func (*GetAllModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{0}
}

func (m *GetAllModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllModel.Unmarshal(m, b)
}
func (m *GetAllModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllModel.Marshal(b, m, deterministic)
}
func (m *GetAllModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllModel.Merge(m, src)
}
func (m *GetAllModel) XXX_Size() int {
	return xxx_messageInfo_GetAllModel.Size(m)
}
func (m *GetAllModel) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllModel.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllModel proto.InternalMessageInfo

type GetByIdModel struct {
	PersonalId           string   `protobuf:"bytes,1,opt,name=PersonalId,proto3" json:"PersonalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdModel) Reset()         { *m = GetByIdModel{} }
func (m *GetByIdModel) String() string { return proto.CompactTextString(m) }
func (*GetByIdModel) ProtoMessage()    {}
func (*GetByIdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{1}
}

func (m *GetByIdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdModel.Unmarshal(m, b)
}
func (m *GetByIdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdModel.Marshal(b, m, deterministic)
}
func (m *GetByIdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdModel.Merge(m, src)
}
func (m *GetByIdModel) XXX_Size() int {
	return xxx_messageInfo_GetByIdModel.Size(m)
}
func (m *GetByIdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdModel.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdModel proto.InternalMessageInfo

func (m *GetByIdModel) GetPersonalId() string {
	if m != nil {
		return m.PersonalId
	}
	return ""
}

type AddPersonModel struct {
	PersonalId           string               `protobuf:"bytes,1,opt,name=PersonalId,proto3" json:"PersonalId,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CityOfBirth          string               `protobuf:"bytes,3,opt,name=CityOfBirth,proto3" json:"CityOfBirth,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=DateOfBirth,proto3" json:"DateOfBirth,omitempty"`
	Height               int32                `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	Weight               int32                `protobuf:"varint,6,opt,name=Weight,proto3" json:"Weight,omitempty"`
	IsMarried            bool                 `protobuf:"varint,7,opt,name=IsMarried,proto3" json:"IsMarried,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddPersonModel) Reset()         { *m = AddPersonModel{} }
func (m *AddPersonModel) String() string { return proto.CompactTextString(m) }
func (*AddPersonModel) ProtoMessage()    {}
func (*AddPersonModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{2}
}

func (m *AddPersonModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPersonModel.Unmarshal(m, b)
}
func (m *AddPersonModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPersonModel.Marshal(b, m, deterministic)
}
func (m *AddPersonModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPersonModel.Merge(m, src)
}
func (m *AddPersonModel) XXX_Size() int {
	return xxx_messageInfo_AddPersonModel.Size(m)
}
func (m *AddPersonModel) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPersonModel.DiscardUnknown(m)
}

var xxx_messageInfo_AddPersonModel proto.InternalMessageInfo

func (m *AddPersonModel) GetPersonalId() string {
	if m != nil {
		return m.PersonalId
	}
	return ""
}

func (m *AddPersonModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddPersonModel) GetCityOfBirth() string {
	if m != nil {
		return m.CityOfBirth
	}
	return ""
}

func (m *AddPersonModel) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *AddPersonModel) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AddPersonModel) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *AddPersonModel) GetIsMarried() bool {
	if m != nil {
		return m.IsMarried
	}
	return false
}

type UpdatePersonModel struct {
	PersonalId           string               `protobuf:"bytes,1,opt,name=PersonalId,proto3" json:"PersonalId,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CityOfBirth          string               `protobuf:"bytes,3,opt,name=CityOfBirth,proto3" json:"CityOfBirth,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=DateOfBirth,proto3" json:"DateOfBirth,omitempty"`
	Height               int32                `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	Weight               int32                `protobuf:"varint,6,opt,name=Weight,proto3" json:"Weight,omitempty"`
	IsMarried            bool                 `protobuf:"varint,7,opt,name=IsMarried,proto3" json:"IsMarried,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdatePersonModel) Reset()         { *m = UpdatePersonModel{} }
func (m *UpdatePersonModel) String() string { return proto.CompactTextString(m) }
func (*UpdatePersonModel) ProtoMessage()    {}
func (*UpdatePersonModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{3}
}

func (m *UpdatePersonModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePersonModel.Unmarshal(m, b)
}
func (m *UpdatePersonModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePersonModel.Marshal(b, m, deterministic)
}
func (m *UpdatePersonModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePersonModel.Merge(m, src)
}
func (m *UpdatePersonModel) XXX_Size() int {
	return xxx_messageInfo_UpdatePersonModel.Size(m)
}
func (m *UpdatePersonModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePersonModel.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePersonModel proto.InternalMessageInfo

func (m *UpdatePersonModel) GetPersonalId() string {
	if m != nil {
		return m.PersonalId
	}
	return ""
}

func (m *UpdatePersonModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePersonModel) GetCityOfBirth() string {
	if m != nil {
		return m.CityOfBirth
	}
	return ""
}

func (m *UpdatePersonModel) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *UpdatePersonModel) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *UpdatePersonModel) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *UpdatePersonModel) GetIsMarried() bool {
	if m != nil {
		return m.IsMarried
	}
	return false
}

type ResponseModel struct {
	Status               ResponseModel_StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=personal.ResponseModel_StatusCode" json:"status,omitempty"`
	Message              string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *any.Any                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ResponseModel) Reset()         { *m = ResponseModel{} }
func (m *ResponseModel) String() string { return proto.CompactTextString(m) }
func (*ResponseModel) ProtoMessage()    {}
func (*ResponseModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{4}
}

func (m *ResponseModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseModel.Unmarshal(m, b)
}
func (m *ResponseModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseModel.Marshal(b, m, deterministic)
}
func (m *ResponseModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseModel.Merge(m, src)
}
func (m *ResponseModel) XXX_Size() int {
	return xxx_messageInfo_ResponseModel.Size(m)
}
func (m *ResponseModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseModel.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseModel proto.InternalMessageInfo

func (m *ResponseModel) GetStatus() ResponseModel_StatusCode {
	if m != nil {
		return m.Status
	}
	return ResponseModel_FAIL
}

func (m *ResponseModel) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseModel) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetResponseModel struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	CityOfBirth          string               `protobuf:"bytes,2,opt,name=CityOfBirth,proto3" json:"CityOfBirth,omitempty"`
	DateOfBirth          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=DateOfBirth,proto3" json:"DateOfBirth,omitempty"`
	Height               int32                `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	Weight               int32                `protobuf:"varint,5,opt,name=Weight,proto3" json:"Weight,omitempty"`
	IsMarried            bool                 `protobuf:"varint,6,opt,name=IsMarried,proto3" json:"IsMarried,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetResponseModel) Reset()         { *m = GetResponseModel{} }
func (m *GetResponseModel) String() string { return proto.CompactTextString(m) }
func (*GetResponseModel) ProtoMessage()    {}
func (*GetResponseModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{5}
}

func (m *GetResponseModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponseModel.Unmarshal(m, b)
}
func (m *GetResponseModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponseModel.Marshal(b, m, deterministic)
}
func (m *GetResponseModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponseModel.Merge(m, src)
}
func (m *GetResponseModel) XXX_Size() int {
	return xxx_messageInfo_GetResponseModel.Size(m)
}
func (m *GetResponseModel) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponseModel.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponseModel proto.InternalMessageInfo

func (m *GetResponseModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetResponseModel) GetCityOfBirth() string {
	if m != nil {
		return m.CityOfBirth
	}
	return ""
}

func (m *GetResponseModel) GetDateOfBirth() *timestamp.Timestamp {
	if m != nil {
		return m.DateOfBirth
	}
	return nil
}

func (m *GetResponseModel) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetResponseModel) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *GetResponseModel) GetIsMarried() bool {
	if m != nil {
		return m.IsMarried
	}
	return false
}

type GetAllResponseModel struct {
	Data                 []*GetResponseModel `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAllResponseModel) Reset()         { *m = GetAllResponseModel{} }
func (m *GetAllResponseModel) String() string { return proto.CompactTextString(m) }
func (*GetAllResponseModel) ProtoMessage()    {}
func (*GetAllResponseModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79cbc148f3076ab, []int{6}
}

func (m *GetAllResponseModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponseModel.Unmarshal(m, b)
}
func (m *GetAllResponseModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponseModel.Marshal(b, m, deterministic)
}
func (m *GetAllResponseModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponseModel.Merge(m, src)
}
func (m *GetAllResponseModel) XXX_Size() int {
	return xxx_messageInfo_GetAllResponseModel.Size(m)
}
func (m *GetAllResponseModel) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponseModel.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponseModel proto.InternalMessageInfo

func (m *GetAllResponseModel) GetData() []*GetResponseModel {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("personal.ResponseModel_StatusCode", ResponseModel_StatusCode_name, ResponseModel_StatusCode_value)
	proto.RegisterType((*GetAllModel)(nil), "personal.GetAllModel")
	proto.RegisterType((*GetByIdModel)(nil), "personal.GetByIdModel")
	proto.RegisterType((*AddPersonModel)(nil), "personal.AddPersonModel")
	proto.RegisterType((*UpdatePersonModel)(nil), "personal.UpdatePersonModel")
	proto.RegisterType((*ResponseModel)(nil), "personal.ResponseModel")
	proto.RegisterType((*GetResponseModel)(nil), "personal.GetResponseModel")
	proto.RegisterType((*GetAllResponseModel)(nil), "personal.GetAllResponseModel")
}

func init() { proto.RegisterFile("api/proto/person/personal.proto", fileDescriptor_e79cbc148f3076ab) }

var fileDescriptor_e79cbc148f3076ab = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x66, 0x1b, 0xe7, 0x6f, 0xdc, 0x94, 0x30, 0xd0, 0x62, 0xdc, 0x96, 0x58, 0x46, 0x48, 0x11,
	0x07, 0x47, 0x0a, 0xb7, 0x8a, 0x4b, 0x92, 0x96, 0x10, 0x89, 0x02, 0x72, 0xa8, 0x90, 0x40, 0x42,
	0xda, 0xe2, 0x6d, 0x6a, 0xe4, 0xd8, 0x96, 0xbd, 0x45, 0x8a, 0x10, 0x17, 0x5e, 0x81, 0x33, 0x6f,
	0xc1, 0x9b, 0xc0, 0x23, 0xf0, 0x04, 0x48, 0xdc, 0x51, 0x76, 0x6d, 0x27, 0x76, 0x08, 0x45, 0x5c,
	0x39, 0xc5, 0xf3, 0xcd, 0xec, 0xcc, 0x7e, 0xf3, 0xed, 0x4c, 0xa0, 0x45, 0x43, 0xb7, 0x13, 0x46,
	0x01, 0x0f, 0x3a, 0x21, 0x8b, 0xe2, 0xc0, 0x4f, 0x7e, 0xa8, 0x67, 0x09, 0x14, 0x6b, 0xa9, 0xad,
	0xef, 0x4d, 0x82, 0x60, 0xe2, 0xb1, 0xce, 0xfc, 0x04, 0xf5, 0xfd, 0x80, 0x53, 0xee, 0x06, 0x7e,
	0x2c, 0xe3, 0xf4, 0x5b, 0x89, 0x57, 0x58, 0xa7, 0x17, 0x67, 0x1d, 0xea, 0xcf, 0x12, 0x57, 0xab,
	0xe8, 0xe2, 0xee, 0x94, 0xc5, 0x9c, 0x4e, 0x43, 0x19, 0x60, 0x36, 0x40, 0x1d, 0x32, 0xde, 0xf3,
	0xbc, 0xe3, 0xc0, 0x61, 0x9e, 0x69, 0xc1, 0xe6, 0x90, 0xf1, 0xfe, 0x6c, 0xe4, 0x08, 0x1b, 0x6f,
	0x03, 0x3c, 0x4b, 0x2e, 0x31, 0x72, 0x34, 0x62, 0x90, 0x76, 0xdd, 0x5e, 0x42, 0xcc, 0x1f, 0x04,
	0xb6, 0x7a, 0x8e, 0x23, 0x91, 0xbf, 0x3a, 0x82, 0x08, 0xca, 0x13, 0x3a, 0x65, 0xda, 0x86, 0xf0,
	0x88, 0x6f, 0x34, 0x40, 0x1d, 0xb8, 0x7c, 0xf6, 0xf4, 0xac, 0xef, 0x46, 0xfc, 0x5c, 0x2b, 0x09,
	0xd7, 0x32, 0x84, 0x0f, 0x40, 0x3d, 0xa4, 0x9c, 0xa5, 0x11, 0x8a, 0x41, 0xda, 0x6a, 0x57, 0xb7,
	0x24, 0x3d, 0x2b, 0xa5, 0x67, 0x3d, 0x4f, 0xe9, 0xd9, 0xcb, 0xe1, 0xb8, 0x03, 0x95, 0x47, 0xcc,
	0x9d, 0x9c, 0x73, 0xad, 0x6c, 0x90, 0x76, 0xd9, 0x4e, 0xac, 0x39, 0xfe, 0x42, 0xe2, 0x15, 0x89,
	0x4b, 0x0b, 0xf7, 0xa0, 0x3e, 0x8a, 0x8f, 0x69, 0x14, 0xb9, 0xcc, 0xd1, 0xaa, 0x06, 0x69, 0xd7,
	0xec, 0x05, 0x60, 0xfe, 0x24, 0x70, 0xed, 0x24, 0x74, 0x28, 0x67, 0xff, 0x17, 0xef, 0x2f, 0x04,
	0x1a, 0x36, 0x8b, 0xc3, 0xc0, 0x8f, 0x99, 0xe4, 0x7c, 0x00, 0x95, 0x98, 0x53, 0x7e, 0x11, 0x0b,
	0xbe, 0x5b, 0x5d, 0xd3, 0xca, 0x9e, 0x70, 0x2e, 0xd0, 0x1a, 0x8b, 0xa8, 0x41, 0xe0, 0x30, 0x3b,
	0x39, 0x81, 0x1a, 0x54, 0xa7, 0x2c, 0x8e, 0xe9, 0x24, 0x6d, 0x49, 0x6a, 0x62, 0x1b, 0x14, 0x87,
	0x72, 0x2a, 0xda, 0xa1, 0x76, 0x6f, 0xac, 0x90, 0xed, 0xf9, 0x33, 0x5b, 0x44, 0x98, 0x77, 0x00,
	0x16, 0x99, 0xb1, 0x06, 0xca, 0xc3, 0xde, 0xe8, 0x71, 0xf3, 0x0a, 0xaa, 0x50, 0x1d, 0x9f, 0x0c,
	0x06, 0x47, 0xe3, 0x71, 0x93, 0x98, 0xdf, 0x08, 0x34, 0x87, 0x8c, 0xe7, 0x6f, 0x9e, 0xaa, 0x41,
	0xd6, 0xab, 0xb1, 0x71, 0xa9, 0x1a, 0xa5, 0x7f, 0x55, 0x43, 0x59, 0xa3, 0x46, 0x79, 0xbd, 0x1a,
	0x95, 0xa2, 0x1a, 0x47, 0x70, 0x5d, 0x4e, 0x6e, 0x9e, 0x98, 0x05, 0xca, 0xe1, 0xbc, 0x79, 0xc4,
	0x28, 0x89, 0xbb, 0x65, 0x82, 0x14, 0x5b, 0x60, 0x8b, 0xb8, 0xee, 0xe7, 0x12, 0x5c, 0x4d, 0x5f,
	0xe9, 0x98, 0x45, 0xef, 0xdc, 0x37, 0x0c, 0x5f, 0x41, 0x3d, 0x1b, 0x6a, 0xd4, 0x16, 0x29, 0xf2,
	0x93, 0xae, 0xdf, 0x5c, 0xa3, 0xb6, 0xb9, 0xfb, 0xf1, 0xeb, 0xf7, 0x4f, 0x1b, 0xdb, 0x66, 0x33,
	0xdb, 0x68, 0xc9, 0xc7, 0x01, 0xb9, 0x87, 0x14, 0x36, 0x97, 0x87, 0x07, 0x77, 0x17, 0x59, 0x56,
	0x86, 0xea, 0xd2, 0x12, 0xfa, 0x6f, 0x4b, 0xbc, 0x85, 0xc6, 0x90, 0x71, 0x99, 0x67, 0xbe, 0xcb,
	0x70, 0x27, 0xd7, 0x86, 0x6c, 0xbd, 0xe9, 0x7f, 0x68, 0x8f, 0x79, 0x57, 0x54, 0x68, 0xe1, 0x7e,
	0xb1, 0x42, 0xe7, 0xfd, 0x62, 0xaa, 0x3f, 0xe0, 0x6b, 0xb1, 0x31, 0x7b, 0x9e, 0x97, 0xd0, 0xd9,
	0xce, 0xa5, 0x4c, 0x17, 0xab, 0xbe, 0x5f, 0x84, 0xf3, 0xc5, 0x34, 0x51, 0x0c, 0x71, 0x85, 0x4e,
	0x1f, 0x5e, 0x66, 0x7f, 0x03, 0xa7, 0x15, 0xf1, 0xc2, 0xee, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0xa2, 0x03, 0x6a, 0x9a, 0x3a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonalServiceClient is the client API for PersonalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonalServiceClient interface {
	AddPerson(ctx context.Context, in *AddPersonModel, opts ...grpc.CallOption) (*ResponseModel, error)
	UpdatePerson(ctx context.Context, in *UpdatePersonModel, opts ...grpc.CallOption) (*ResponseModel, error)
	GetPersonById(ctx context.Context, in *GetByIdModel, opts ...grpc.CallOption) (*GetResponseModel, error)
	GetAllPerson(ctx context.Context, in *GetAllModel, opts ...grpc.CallOption) (*GetAllResponseModel, error)
}

type personalServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonalServiceClient(cc *grpc.ClientConn) PersonalServiceClient {
	return &personalServiceClient{cc}
}

func (c *personalServiceClient) AddPerson(ctx context.Context, in *AddPersonModel, opts ...grpc.CallOption) (*ResponseModel, error) {
	out := new(ResponseModel)
	err := c.cc.Invoke(ctx, "/personal.PersonalService/AddPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personalServiceClient) UpdatePerson(ctx context.Context, in *UpdatePersonModel, opts ...grpc.CallOption) (*ResponseModel, error) {
	out := new(ResponseModel)
	err := c.cc.Invoke(ctx, "/personal.PersonalService/UpdatePerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personalServiceClient) GetPersonById(ctx context.Context, in *GetByIdModel, opts ...grpc.CallOption) (*GetResponseModel, error) {
	out := new(GetResponseModel)
	err := c.cc.Invoke(ctx, "/personal.PersonalService/GetPersonById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personalServiceClient) GetAllPerson(ctx context.Context, in *GetAllModel, opts ...grpc.CallOption) (*GetAllResponseModel, error) {
	out := new(GetAllResponseModel)
	err := c.cc.Invoke(ctx, "/personal.PersonalService/GetAllPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonalServiceServer is the server API for PersonalService service.
type PersonalServiceServer interface {
	AddPerson(context.Context, *AddPersonModel) (*ResponseModel, error)
	UpdatePerson(context.Context, *UpdatePersonModel) (*ResponseModel, error)
	GetPersonById(context.Context, *GetByIdModel) (*GetResponseModel, error)
	GetAllPerson(context.Context, *GetAllModel) (*GetAllResponseModel, error)
}

// UnimplementedPersonalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPersonalServiceServer struct {
}

func (*UnimplementedPersonalServiceServer) AddPerson(ctx context.Context, req *AddPersonModel) (*ResponseModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPerson not implemented")
}
func (*UnimplementedPersonalServiceServer) UpdatePerson(ctx context.Context, req *UpdatePersonModel) (*ResponseModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePerson not implemented")
}
func (*UnimplementedPersonalServiceServer) GetPersonById(ctx context.Context, req *GetByIdModel) (*GetResponseModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonById not implemented")
}
func (*UnimplementedPersonalServiceServer) GetAllPerson(ctx context.Context, req *GetAllModel) (*GetAllResponseModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPerson not implemented")
}

func RegisterPersonalServiceServer(s *grpc.Server, srv PersonalServiceServer) {
	s.RegisterService(&_PersonalService_serviceDesc, srv)
}

func _PersonalService_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPersonModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonalServiceServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personal.PersonalService/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonalServiceServer).AddPerson(ctx, req.(*AddPersonModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonalService_UpdatePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePersonModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonalServiceServer).UpdatePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personal.PersonalService/UpdatePerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonalServiceServer).UpdatePerson(ctx, req.(*UpdatePersonModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonalService_GetPersonById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonalServiceServer).GetPersonById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personal.PersonalService/GetPersonById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonalServiceServer).GetPersonById(ctx, req.(*GetByIdModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonalService_GetAllPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonalServiceServer).GetAllPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/personal.PersonalService/GetAllPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonalServiceServer).GetAllPerson(ctx, req.(*GetAllModel))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "personal.PersonalService",
	HandlerType: (*PersonalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _PersonalService_AddPerson_Handler,
		},
		{
			MethodName: "UpdatePerson",
			Handler:    _PersonalService_UpdatePerson_Handler,
		},
		{
			MethodName: "GetPersonById",
			Handler:    _PersonalService_GetPersonById_Handler,
		},
		{
			MethodName: "GetAllPerson",
			Handler:    _PersonalService_GetAllPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/person/personal.proto",
}
