// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/response/response.proto

package response

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseBase_StatusCode int32

const (
	ResponseBase_FAIL    ResponseBase_StatusCode = 0
	ResponseBase_SUCCESS ResponseBase_StatusCode = 1
)

var ResponseBase_StatusCode_name = map[int32]string{
	0: "FAIL",
	1: "SUCCESS",
}

var ResponseBase_StatusCode_value = map[string]int32{
	"FAIL":    0,
	"SUCCESS": 1,
}

func (x ResponseBase_StatusCode) String() string {
	return proto.EnumName(ResponseBase_StatusCode_name, int32(x))
}

func (ResponseBase_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28126298e1332ffa, []int{0, 0}
}

type ResponseBase struct {
	Status               ResponseBase_StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=response.ResponseBase_StatusCode" json:"status,omitempty"`
	Message              string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *any.Any                `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ResponseBase) Reset()         { *m = ResponseBase{} }
func (m *ResponseBase) String() string { return proto.CompactTextString(m) }
func (*ResponseBase) ProtoMessage()    {}
func (*ResponseBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_28126298e1332ffa, []int{0}
}

func (m *ResponseBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseBase.Unmarshal(m, b)
}
func (m *ResponseBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseBase.Marshal(b, m, deterministic)
}
func (m *ResponseBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseBase.Merge(m, src)
}
func (m *ResponseBase) XXX_Size() int {
	return xxx_messageInfo_ResponseBase.Size(m)
}
func (m *ResponseBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseBase.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseBase proto.InternalMessageInfo

func (m *ResponseBase) GetStatus() ResponseBase_StatusCode {
	if m != nil {
		return m.Status
	}
	return ResponseBase_FAIL
}

func (m *ResponseBase) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseBase) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("response.ResponseBase_StatusCode", ResponseBase_StatusCode_name, ResponseBase_StatusCode_value)
	proto.RegisterType((*ResponseBase)(nil), "response.ResponseBase")
}

func init() { proto.RegisterFile("proto/response/response.proto", fileDescriptor_28126298e1332ffa) }

var fileDescriptor_28126298e1332ffa = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x85, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0x1c, 0x30, 0xbe, 0x94, 0x64, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x58, 0x3c, 0xa9, 0x34,
	0x4d, 0x3f, 0x31, 0xaf, 0x12, 0xa2, 0x48, 0x69, 0x13, 0x23, 0x17, 0x4f, 0x10, 0x54, 0x9d, 0x53,
	0x62, 0x71, 0xaa, 0x90, 0x25, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x9f, 0x91, 0xa2, 0x1e, 0xdc, 0x58, 0x64, 0x75, 0x7a, 0xc1, 0x60, 0x45, 0xce, 0xf9,
	0x29, 0xa9, 0x41, 0x50, 0x0d, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x06, 0x17, 0x4b, 0x4a, 0x62, 0x49,
	0xa2, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x88, 0x1e, 0xc4, 0x3d, 0x7a, 0x30, 0xf7, 0xe8,
	0x39, 0xe6, 0x55, 0x06, 0x81, 0x55, 0x28, 0x29, 0x73, 0x71, 0x21, 0x4c, 0x16, 0xe2, 0xe0, 0x62,
	0x71, 0x73, 0xf4, 0xf4, 0x11, 0x60, 0x10, 0xe2, 0xe6, 0x62, 0x0f, 0x0e, 0x75, 0x76, 0x76, 0x0d,
	0x0e, 0x16, 0x60, 0x74, 0xe2, 0x8a, 0x82, 0xfb, 0x2d, 0x89, 0x0d, 0x6c, 0x88, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xfd, 0xcf, 0x65, 0x9d, 0x0d, 0x01, 0x00, 0x00,
}
